### ISSUE TITLE
The link on readme is not working

### ISSUE THREAD

**Issue by Kachulio1** [steadfasterX/android_device_lge_h815#5]
<img width="332" alt="screen shot 2019-02-05 at 16 24 12" src="https://user-images.githubusercontent.com/22243090/52276211-a7303900-2962-11e9-9fa7-e86ebc724b34.png">

**Comment by Kachulio1** [comment]
also, I have lgg4 h81021y is it possible to root it now

**Comment by steadfasterX** [comment]
Link works perfect here.
The other q is answered in the UsU thread and is no.
